front: make Select more genric
osrd-project/osrd-ui pull request #70
Opened 2024-05-27 10:07 UTC by kmer2016

2024-05-28 10:04 UTC, clarani requested changes

2024-05-28 10:04 UTC, clarani commented on ui-core/src/stories/Select.stories.tsx
Can you change the title of the story to 'core/Select' (l36) ?

2024-05-28 10:04 UTC, clarani commented on ui-core/src/stories/Select.stories.tsx
> +    onChange: (option?: unknown) => console.log(option),
I don't really like this, can you rather define a wrapper like this ? 
```
const SelectWrapper = (props: SelectProps<Option>) => {
  return <Select {...props} />;
};
```
You can use it instead of the Select l16 and then change your functions:
```suggestion
    getOptionLabel: (option: Option) => option.label,
    getOptionValue: (option: Option) => option.value,
    onChange: (option?: Option) => console.log(option),
```

2024-05-28 10:04 UTC, clarani commented on ui-core/src/components/Select.tsx
> +    value?: T;
If value can be undefined, it should be handle in T
```suggestion
    value: T;
```

2024-05-28 10:04 UTC, clarani commented on ui-core/src/components/Select.tsx
> +    onChange: (option?: T) => void;
```suggestion
    onChange: (option: T) => void;
```

2024-05-28 10:04 UTC, clarani commented on ui-core/src/components/Select.tsx
> +  const [selectedOption, setSelectedOption] = useState<T | undefined>(value);
```suggestion
  const [selectedOption, setSelectedOption] = useState<T>(value);
```

2024-05-28 10:04 UTC, clarani commented on ui-core/src/components/Select.tsx
> +        })}
```suggestion
        className={cx('custom-select', `${statusWithMessage}`, {
          'placeholder-selected': !selectedOption,
          small,
          'read-only': readOnly,
        })}
```

2024-06-04 15:48 UTC, kmer2016 commented on ui-core/src/components/Select.tsx
> +    onChange: (option?: T) => void;
I keep it like this, because the user can select the placeholder, in that case, the option can be undefined

2024-06-04 15:51 UTC, kmer2016 commented on ui-core/src/components/Select.tsx
> +  const [selectedOption, setSelectedOption] = useState<T | undefined>(value);
I have kept it that way for the same reason I mentioned in the comment above.

2024-06-20 08:30 UTC, clarani commented on ui-core/src/components/Select.tsx
> +        className={cx('custom-select', `${statusWithMessage?.status || ''}`, {
```suggestion
        className={cx('custom-select', statusWithMessage?.status, {
```

2024-06-20 13:31 UTC, clarani reviewed
Can you squash your commits and rephrase it ? Here is an example: "core: make select more generic"

2024-06-20 14:39 UTC, clarani approved these changes
LGTM

2024-06-20 14:40 UTC, merged