core, timePicker: fix the ability to control the component from parent
osrd-project/osrd-ui pull request #81
Opened 2024-06-26 17:17 UTC by kmer2016

fix #80

2024-06-27 08:33 UTC, SharglutDev requested changes

2024-06-27 08:33 UTC, SharglutDev commented on ui-core/src/components/inputs/TimePicker.tsx
> +    <div className="time-grid">
Looks like the gap here is bigger than the one from sketch (should be 2px)

2024-06-27 08:53 UTC, Yohh reviewed
it seems we have a problem with `hours` & `minutes` props

they don't change anything and they aren't absolute (set minus and reload, the timer collapse)

[Screencast from 2024-06-27 10-51-44.webm](https://github.com/OpenRailAssociation/osrd-ui/assets/20640252/81158a45-3a3e-473d-8a9f-73a2ad08cd09)

2024-06-27 08:58 UTC, Yohh commented on ui-core/src/components/inputs/TimePicker.tsx
> +    <div className="time-grid">
the value is weird, maybe an update of the mockup

[Screencast from 2024-06-27 10-58-03.webm](https://github.com/OpenRailAssociation/osrd-ui/assets/20640252/be59b4ee-313f-4e75-8e73-9a874fc18dc5)

2024-06-27 17:42 UTC, SharglutDev requested changes

2024-06-27 17:42 UTC, SharglutDev commented on ui-core/src/components/inputs/TimePicker.tsx
> +  const selectedTime = `${formatTimeValue(hours, 23)}:${formatTimeValue(hours, 59)}`;
```suggestion
  const selectedTime = `${formatTimeValue(hours, 23)}:${formatTimeValue(minutes, 59)}`;
```

2024-06-28 14:45 UTC, kmer2016 commented on ui-core/src/components/inputs/TimePicker.tsx
> +  const selectedTime = `${formatTimeValue(hours, 23)}:${formatTimeValue(hours, 59)}`;
Done !

2024-06-28 15:12 UTC, SharglutDev approved these changes
Lgtm and tested, good job !

2024-07-02 13:52 UTC, merged